import html2canvas from 'html2canvas';
import { BorderStyle, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import jsPDF from 'jspdf';

// ---------------------------------------------------------------------------
// Shared markdown-stripping helpers
// ---------------------------------------------------------------------------

function stripHeadingMarkers(raw: string): string {
  return raw.replace(/^#{1,6}\s*/, '').trim();
}

function stripInlineMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/_{1,2}(.+?)_{1,2}/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/<[^>]+>/g, '')
    .trim();
}

function normalizeExportText(text: string): string {
  return text
    .replace(/^\s*#{1,6}\s*/, '')
    .replace(/^\s*[%•]\s*/, '')
    .replace(/^\s*[-*]\s+/, '')
    .replace(/Generated by Aur\.a(?:\s*[·|].*)?/gi, '')
    .replace(/Generated by Aura(?:\s*[·|].*)?/gi, '')
    .trim();
}

type ParsedToken =
  | { kind: 'name'; text: string }
  | { kind: 'contact'; text: string }
  | { kind: 'divider' }
  | { kind: 'heading'; text: string }
  | { kind: 'bullet'; text: string }
  | { kind: 'entry'; left: string; right: string }
  | { kind: 'plain'; text: string };

function parseLineToken(raw: string): ParsedToken | null {
  if (/^#{1,6}\s/.test(raw)) {
    return { kind: 'heading', text: stripInlineMarkdown(stripHeadingMarkers(raw)).toUpperCase() };
  }
  if (/^-{3,}$/.test(raw.trim()) || /^\*{3,}$/.test(raw.trim()) || /^_{3,}$/.test(raw.trim())) {
    return { kind: 'divider' };
  }
  if (/^[-*%]\s/.test(raw) || raw.trimStart().startsWith('\u2022')) {
    return { kind: 'bullet', text: normalizeExportText(stripInlineMarkdown(raw.replace(/^[-*%\u2022]\s*/, '').trim())) };
  }
  const trimmed = raw.trim();
  if (!trimmed) return null;
  const clean = normalizeExportText(stripInlineMarkdown(trimmed));
  if (clean.length > 3 && clean === clean.toUpperCase() && !clean.includes('@') && !/\d{4}/.test(clean)) {
    return { kind: 'heading', text: clean };
  }
  return { kind: 'plain', text: clean };
}

function parseCVTokens(cvText: string): ParsedToken[] {
  const rawLines = cvText
    .split('\n')
    .map(normalizeExportText)
    .filter((line) => line.length > 0 || !/Generated by Aur\.a|Generated by Aura/i.test(line));
  const tokens: ParsedToken[] = [];
  let nameEmitted = false;
  let contactEmitted = false;
  let headersDone = false;

  for (let i = 0; i < rawLines.length; i++) {
    const raw = rawLines[i];
    const trimmed = raw.trim();

    if (!headersDone) {
      if (!trimmed) continue;
      if (!nameEmitted) {
        tokens.push({ kind: 'name', text: stripInlineMarkdown(stripHeadingMarkers(trimmed)) });
        nameEmitted = true;
        continue;
      }
      if (!contactEmitted) {
        tokens.push({ kind: 'contact', text: stripInlineMarkdown(trimmed) });
        tokens.push({ kind: 'divider' });
        contactEmitted = true;
        headersDone = true;
        continue;
      }
    }

    if (!trimmed) continue;

    const token = parseLineToken(raw);
    if (!token) continue;

    if (token.kind === 'plain') {
      const datePattern = /(\d{4}|Present|present)/;
      if (datePattern.test(token.text)) {
        const splitMatch = token.text.match(/^(.+?)\s{2,}(.+)$/);
        if (splitMatch) {
          tokens.push({ kind: 'entry', left: splitMatch[1].trim(), right: splitMatch[2].trim() });
          continue;
        }
      }
      if (/^\*\*/.test(raw.trim())) {
        tokens.push({ kind: 'entry', left: token.text, right: '' });
        continue;
      }
    }

    tokens.push(token);
  }

  return tokens;
}

// ---------------------------------------------------------------------------
// Section routing helpers (mirrors CVBuilderPage logic)
// ---------------------------------------------------------------------------

const LEFT_SECTIONS = new Set([
  'SUMMARY', 'PERSONAL SUMMARY', 'PROFILE', 'OBJECTIVE',
  'EXPERIENCE', 'WORK EXPERIENCE', 'EMPLOYMENT', 'EMPLOYMENT HISTORY',
  'CUSTOM', 'CERTIFICATIONS', 'CERTIFICATIONS AND ACHIEVEMENTS', 'PROJECTS', 'CERTIFICATES',
  'LANGUAGES', 'TRAINING', 'COURSES', 'TRAINING AND COURSES',
]);

const RIGHT_SECTIONS = new Set([
  'KEY ACHIEVEMENTS', 'ACHIEVEMENTS',
  'SKILLS', 'TECHNICAL SKILLS', 'SOFT SKILLS',
  'CORE COMPETENCIES', 'COMPETENCIES',
  'EDUCATION', 'EDUCATION AND QUALIFICATIONS', 'QUALIFICATIONS',
  'REFERENCES',
]);

function getSectionSide(heading: string): 'left' | 'right' {
  const upper = heading.toUpperCase().trim();
  if (LEFT_SECTIONS.has(upper)) return 'left';
  if (RIGHT_SECTIONS.has(upper)) return 'right';
  for (const s of LEFT_SECTIONS) if (upper.includes(s)) return 'left';
  for (const s of RIGHT_SECTIONS) if (upper.includes(s)) return 'right';
  return 'left';
}

function canonicalSectionHeading(heading: string): string {
  const upper = normalizeExportText(heading).toUpperCase().trim();
  if (upper.includes('CORE COMPETENC')) return 'SKILLS & CORE COMPETENCIES';
  if (upper === 'SKILLS' || upper.includes('TECHNICAL SKILLS') || upper.includes('SOFT SKILLS')) {
    return 'SKILLS & CORE COMPETENCIES';
  }
  if (upper.includes('KEY ACHIEVEMENT') || upper === 'ACHIEVEMENTS') return 'KEY ACHIEVEMENTS';
  if (upper.includes('PERSONAL SUMMARY') || upper === 'PROFILE' || upper === 'OBJECTIVE') return 'SUMMARY';
  return upper;
}

function normalizeSections(sections: ColSection[]): ColSection[] {
  const merged = new Map<string, ColSection>();
  const experienceText = new Set(
    sections
      .filter((section) => /EXPERIENCE|EMPLOYMENT/i.test(section.heading))
      .flatMap((section) => section.tokens)
      .filter((token): token is Extract<ParsedToken, { kind: 'bullet' | 'plain' }> => token.kind === 'bullet' || token.kind === 'plain')
      .map((token) => token.text.toLowerCase().replace(/\W+/g, ' ').trim())
  );

  for (const section of sections) {
    const heading = canonicalSectionHeading(section.heading);
    const tokens = section.tokens.filter((token) => {
      if (token.kind === 'plain' || token.kind === 'bullet') return Boolean(token.text.trim());
      return true;
    });
    if (!tokens.length) continue;

    const filteredTokens = heading === 'KEY ACHIEVEMENTS'
      ? tokens.filter((token) => {
          if (token.kind !== 'plain' && token.kind !== 'bullet') return true;
          return !experienceText.has(token.text.toLowerCase().replace(/\W+/g, ' ').trim());
        })
      : tokens;
    if (!filteredTokens.length) continue;

    const existing = merged.get(heading);
    if (existing) {
      const seen = new Set(existing.tokens.map((token) => JSON.stringify(token)));
      existing.tokens.push(...filteredTokens.filter((token) => !seen.has(JSON.stringify(token))));
    } else {
      merged.set(heading, { heading, tokens: filteredTokens });
    }
  }

  return [...merged.values()];
}

// ---------------------------------------------------------------------------
// Language proficiency bar parser
// ---------------------------------------------------------------------------

function parseLanguageLine(text: string): { lang: string; level: number } | null {
  const patterns = [/^(.+?)[\s\-–:]+(.+)$/, /^(.+?)\s+\((.+?)\)$/];
  const levels: Record<string, number> = {
    native: 5, fluent: 5, advanced: 4, proficient: 4,
    intermediate: 3, conversational: 2, basic: 1, beginner: 1,
  };
  for (const pat of patterns) {
    const m = text.match(pat);
    if (m) {
      const score = levels[m[2].trim().toLowerCase()];
      if (score !== undefined) return { lang: m[1].trim(), level: score };
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Columnar token structure
// ---------------------------------------------------------------------------

interface ColSection {
  heading: string;
  tokens: ParsedToken[];
}

function buildColumns(tokens: ParsedToken[]): {
  name: string;
  contact: string;
  left: ColSection[];
  right: ColSection[];
} {
  let name = '';
  let contact = '';
  const left: ColSection[] = [];
  const right: ColSection[] = [];
  let currentSide: 'left' | 'right' = 'left';
  let currentSection: ColSection | null = null;

  const flush = () => {
    if (!currentSection) return;
    if (currentSide === 'left') left.push(currentSection);
    else right.push(currentSection);
    currentSection = null;
  };

  for (const token of tokens) {
    if (token.kind === 'name') { name = token.text; continue; }
    if (token.kind === 'contact') { if (!contact) contact = token.text; continue; }
    if (token.kind === 'divider') continue;
    if (token.kind === 'heading') {
      flush();
      currentSide = getSectionSide(token.text);
      currentSection = { heading: token.text, tokens: [] };
      continue;
    }
    if (currentSection) currentSection.tokens.push(token);
  }
  flush();

  return { name, contact, left: normalizeSections(left), right: normalizeSections(right) };
}

// ---------------------------------------------------------------------------
// Helper: safe filename part
// ---------------------------------------------------------------------------

function safeFilePart(value: string): string {
  return value.replace(/[^a-z0-9]/gi, '-').replace(/-+/g, '-').toLowerCase() || 'cv';
}

const EXPORT_PAGE_WIDTH_PX = 794;

function getCvPreviewElement(): HTMLElement | null {
  return document.getElementById('cv-preview');
}

async function exportCvPreviewToPdf(fileNameBase: string): Promise<void> {
  const preview = getCvPreviewElement();
  if (!preview) {
    return;
  }

  const canvas = await html2canvas(preview, {
    backgroundColor: '#ffffff',
    scale: 2,
    useCORS: true,
    allowTaint: true,
    logging: false,
    width: EXPORT_PAGE_WIDTH_PX,
    height: Math.max(preview.scrollHeight, 1100),
    scrollX: 0,
    scrollY: 0,
    windowWidth: EXPORT_PAGE_WIDTH_PX,
    windowHeight: 1123,
  });

  const doc = new jsPDF({ unit: 'pt', format: 'a4', compress: true });
  const pageWidth = 794;
  const pageHeight = 1123;
  const imgWidth = pageWidth;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  const totalPages = Math.max(1, Math.ceil(imgHeight / pageHeight));
  let cursorY = 0;

  for (let page = 0; page < totalPages; page += 1) {
    if (page > 0) doc.addPage();
    const pageImgHeight = Math.min(imgHeight - page * pageHeight, pageHeight);
    doc.addImage(
      canvas.toDataURL('image/png'),
      'PNG',
      0,
      0,
      imgWidth,
      pageImgHeight,
      undefined,
      'FAST'
    );
    cursorY = page * pageHeight;
    if (page < totalPages - 1) {
      doc.addPage();
    }
  }

  if (totalPages > 1) {
    doc.deletePage(totalPages + 1);
  }
  doc.save(`${safeFilePart(fileNameBase)}.pdf`);
}

function buildWordSectionChildren(section: ColSection, isRight = false): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: section.heading.toUpperCase(),
      heading: HeadingLevel.HEADING_3,
      spacing: { after: 120 },
      border: { bottom: { color: '000000', style: BorderStyle.SINGLE, size: 1 } },
    }),
  ];

  for (const token of section.tokens) {
    if (token.kind === 'entry') {
      const content = token.right ? `${token.left} — ${token.right}` : token.left;
      paragraphs.push(new Paragraph({
        children: [
          new TextRun({ text: content, bold: true, size: isRight ? 18 : 20 }),
        ],
        spacing: { after: 50 },
      }));
    } else if (token.kind === 'bullet') {
      paragraphs.push(new Paragraph({
        text: `• ${token.text}`,
        spacing: { after: 50 },
      }));
    } else if (token.kind === 'plain' || token.kind === 'heading') {
      paragraphs.push(new Paragraph({
        text: token.kind === 'heading' ? token.text.toUpperCase() : token.text,
        spacing: { after: 40 },
        style: token.kind === 'heading' ? 'Heading4' : undefined,
      }));
    }
  }

  return paragraphs;
}

function buildWordDocumentDto(name: string, contact: string, subtitle: string, left: ColSection[], right: ColSection[]): Document {
  const rows: TableRow[] = [];
  const maxSections = Math.max(left.length, right.length);

  for (let i = 0; i < maxSections; i += 1) {
    const leftCellChildren = left[i] ? buildWordSectionChildren(left[i], false) : [new Paragraph('')];
    const rightCellChildren = right[i] ? buildWordSectionChildren(right[i], true) : [new Paragraph('')];
    rows.push(
      new TableRow({
        children: [
          new TableCell({
            children: leftCellChildren,
            width: { size: 50, type: WidthType.PERCENTAGE },
            borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE }, insideHorizontal: { style: BorderStyle.NONE }, insideVertical: { style: BorderStyle.NONE } },
          }),
          new TableCell({
            children: rightCellChildren,
            width: { size: 50, type: WidthType.PERCENTAGE },
            borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE }, insideHorizontal: { style: BorderStyle.NONE }, insideVertical: { style: BorderStyle.NONE } },
          }),
        ],
      })
    );
  }

  const contactLine = contact ? contact.replace(/\s*[|•·]\s*/g, ' • ') : '';

  return new Document({
    sections: [{
      properties: {
        page: { margin: { top: 720, right: 720, bottom: 720, left: 720 } },
      },
      children: [
        new Paragraph({
          text: name.toUpperCase(),
          alignment: 'center',
          heading: HeadingLevel.TITLE,
          spacing: { after: 160 },
        }),
        ...(subtitle ? [new Paragraph({ text: subtitle, alignment: 'center', spacing: { after: 160 } })] : []),
        ...(contactLine ? [new Paragraph({ text: contactLine, alignment: 'center', spacing: { after: 200 } })] : []),
        new Paragraph({
          text: '',
          spacing: { after: 80 },
        }),
        new Table({
          rows,
          width: { size: 100, type: WidthType.PERCENTAGE },
          borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE }, insideHorizontal: { style: BorderStyle.NONE }, insideVertical: { style: BorderStyle.NONE } },
          layout: 'fixed',
        }),
      ],
    }],
  });
}

// ---------------------------------------------------------------------------
// Legacy single-column PDF (kept for backward-compat)
// ---------------------------------------------------------------------------

export function downloadCVAsPDF(cvText: string, jobTitle: string): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 56;
  const marginRight = 56;
  const marginTop = 56;
  const marginBottom = 56;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let y = marginTop;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Personalised CV \u2014 ${jobTitle}`, pageWidth / 2, y, { align: 'center' });
  y += 4;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 20;

  const lines = cvText.split('\n').map(normalizeExportText);

  for (const raw of lines) {
    const line = raw.trimEnd();
    const isSectionHeading =
      line.trim().length > 0 &&
      line.trim() === line.trim().toUpperCase() &&
      line.trim().length > 3;

    if (isSectionHeading) {
      y += 6;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      doc.text(line.trim(), marginLeft, y);
      y += 3;
      doc.setDrawColor(160, 160, 160);
      doc.setLineWidth(0.4);
      doc.line(marginLeft, y, pageWidth - marginRight, y);
      y += 12;
      continue;
    }

    if (line.trim() === '') { y += 6; continue; }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(30, 30, 30);

    const wrapped = doc.splitTextToSize(line, contentWidth);
    for (const wrappedLine of wrapped) {
      if (y + 14 > pageHeight - marginBottom) {
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.5);
        doc.line(marginLeft, pageHeight - marginBottom + 6, pageWidth - marginRight, pageHeight - marginBottom + 6);
        doc.addPage();
        y = marginTop;
      }
      doc.text(wrappedLine, marginLeft, y);
      y += 14;
    }
  }

  doc.save(`personalised-cv-${safeFilePart(jobTitle)}.pdf`);
}

// ---------------------------------------------------------------------------
// Two-column PDF download
// ---------------------------------------------------------------------------

export function downloadATSReadableCVAsPDF(cvText: string, fileNameBase: string): void {
  const previewNode = getCvPreviewElement();
  if (previewNode) {
    void exportCvPreviewToPdf(fileNameBase);
    return;
  }

  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const marginT = 44;
  const marginB = 44;
  const marginL = 44;
  const marginR = 44;

  const bodyW = pageW - marginL - marginR;
  const colGap = 12;
  const leftW = Math.floor(bodyW * 0.635);
  const rightW = bodyW - leftW - colGap;
  const leftX = marginL;
  const rightX = marginL + leftW + colGap;

  const BLUE = [26, 115, 232] as [number, number, number];
  const DARK = [51, 51, 51] as [number, number, number];
  const GRAY = [107, 114, 128] as [number, number, number];
  const LIGHT_GRAY = [209, 213, 219] as [number, number, number];

  const lhBody = 14;
  const lhSmall = 12.5;

  let leftY = marginT;
  let rightY = marginT;

  const tokens = parseCVTokens(cvText);
  const { name, contact, left, right } = buildColumns(tokens);
  const contactParts = contact.split(/\s*[|•·]\s*/).filter(Boolean);
  const subtitle = contactParts.shift() || '';

  let hY = marginT;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...DARK);
  doc.text(name.toUpperCase(), pageW / 2, hY, { align: 'center' });
  hY += 18;

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...BLUE);
    doc.text(subtitle, pageW / 2, hY, { align: 'center' });
    hY += 13;
  }

  if (contactParts.length) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    const contactLine = contactParts.join('   ·   ');
    doc.text(contactLine, pageW / 2, hY, { align: 'center' });
    hY += 12;
  }

  doc.setDrawColor(...DARK);
  doc.setLineWidth(1);
  doc.line(marginL, hY, pageW - marginR, hY);
  hY += 14;

  leftY = hY;
  rightY = hY;

  const ensureSpace = (colX: number, neededH: number, colYRef: { v: number }) => {
    if (colYRef.v + neededH <= pageH - marginB) return;
    doc.addPage();
    leftY = marginT;
    rightY = marginT;
    colYRef.v = marginT;
  };

  const renderSection = (
    section: ColSection,
    colX: number,
    colWidth: number,
    colYRef: { v: number }
  ) => {
    const isLanguages = /LANGUAGE/i.test(section.heading);
    const isRight = colX === rightX;

    ensureSpace(colX, 22, colYRef);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(isRight ? 8.5 : 9);
    doc.setTextColor(...DARK);
    doc.text(section.heading.toUpperCase(), colX, colYRef.v);
    colYRef.v += isRight ? 5 : 6;
    doc.setDrawColor(...DARK);
    doc.setLineWidth(0.8);
    doc.line(colX, colYRef.v, colX + colWidth, colYRef.v);
    colYRef.v += isRight ? 9 : 10;

    for (const token of section.tokens) {
      if (token.kind === 'entry') {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(isRight ? 8.5 : 9.5);
        doc.setTextColor(...DARK);
        const leftMaxW = token.right ? Math.max(40, colWidth * 0.65) : colWidth;
        const leftWrapped = doc.splitTextToSize(token.left, leftMaxW);
        ensureSpace(colX, Math.max(lhBody, leftWrapped.length * lhSmall), colYRef);
        const entryY = colYRef.v;
        for (const wrappedLine of leftWrapped) {
          ensureSpace(colX, lhSmall, colYRef);
          doc.text(wrappedLine, colX, colYRef.v);
          colYRef.v += lhSmall;
        }
        if (token.right) {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.setTextColor(...GRAY);
          doc.text(token.right, colX + colWidth, entryY, { align: 'right' });
        }
      } else if (token.kind === 'bullet') {
        const bulletW = colWidth - 10;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(isRight ? 8 : 8.5);
        doc.setTextColor(...DARK);
        const wrapped = doc.splitTextToSize(token.text, bulletW);
        ensureSpace(colX, Math.max(lhSmall, wrapped.length * lhSmall), colYRef);
        doc.setTextColor(...BLUE);
        doc.circle(colX + 2, colYRef.v - 3, 1.4, 'F');
        doc.setTextColor(...DARK);
        for (let wi = 0; wi < wrapped.length; wi++) {
          ensureSpace(colX, lhSmall, colYRef);
          doc.text(wrapped[wi], colX + 8, colYRef.v);
          colYRef.v += wi < wrapped.length - 1 ? lhSmall : lhSmall - 1;
        }
      } else if (token.kind === 'plain') {
        if (isLanguages) {
          const parsed = parseLanguageLine(token.text);
          if (parsed) {
            ensureSpace(colX, 14, colYRef);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8.5);
            doc.setTextColor(...DARK);
            doc.text(parsed.lang, colX, colYRef.v);
            const barStartX = colX + 62;
            const barW = 16;
            const barH = 5;
            const barGap = 3;
            const barY = colYRef.v - barH + 1;
            for (let n = 1; n <= 5; n++) {
              const bx = barStartX + (n - 1) * (barW + barGap);
              if (n <= parsed.level) {
                doc.setFillColor(...BLUE);
              } else {
                doc.setFillColor(...LIGHT_GRAY);
              }
              doc.roundedRect(bx, barY, barW, barH, 2, 2, 'F');
            }
            colYRef.v += 12;
            continue;
          }
        }
        ensureSpace(colX, lhSmall, colYRef);
        const wrapped = doc.splitTextToSize(token.text, colWidth);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(isRight ? 8 : 8.5);
        doc.setTextColor(80, 80, 80);
        for (const wl of wrapped) {
          ensureSpace(colX, lhSmall, colYRef);
          doc.text(wl, colX, colYRef.v);
          colYRef.v += lhSmall;
        }
      } else if (token.kind === 'heading') {
        ensureSpace(colX, lhSmall, colYRef);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(isRight ? 7.5 : 8.5);
        doc.setTextColor(...DARK);
        doc.text(token.text.toUpperCase(), colX, colYRef.v);
        colYRef.v += lhSmall - 1;
      }
    }

    colYRef.v += 8;
  };

  const leftRef = { v: leftY };
  const rightRef = { v: rightY };

  for (const section of left) {
    renderSection(section, leftX, leftW, leftRef);
    leftY = leftRef.v;
  }
  for (const section of right) {
    renderSection(section, rightX, rightW, rightRef);
    rightY = rightRef.v;
  }

  const separatorH = Math.max(leftY, rightY) - hY;
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(marginL + leftW + colGap / 2, hY, marginL + leftW + colGap / 2, hY + separatorH);

  doc.save(`${safeFilePart(fileNameBase)}.pdf`);
}

// ---------------------------------------------------------------------------
// HTML escape helper
// ---------------------------------------------------------------------------

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ---------------------------------------------------------------------------
// Two-column Word (HTML) download
// ---------------------------------------------------------------------------

export async function downloadATSReadableCVAsWord(cvText: string, fileNameBase: string): Promise<void> {
  const tokens = parseCVTokens(cvText);
  const { name, contact, left, right } = buildColumns(tokens);
  const contactParts = contact.split(/\s*[|•·]\s*/).filter(Boolean);
  const subtitle = contactParts.shift() || '';

  const doc = buildWordDocumentDto(name || 'YOUR NAME', contact, subtitle, left, right);
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${safeFilePart(fileNameBase)}.docx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
