import jsPDF from 'jspdf';

/**
 * Generates a clean, ATS-friendly PDF from plain-text CV content.
 * Uses jsPDF to write real selectable text (not an image) so the PDF
 * passes ATS parsers.
 */
export function downloadCVAsPDF(cvText: string, jobTitle: string): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 56;
  const marginRight = 56;
  const marginTop = 56;
  const marginBottom = 56;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let y = marginTop;

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  const headerText = `Personalised CV — ${jobTitle}`;
  doc.text(headerText, pageWidth / 2, y, { align: 'center' });
  y += 4;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 20;

  // ── Body: parse lines and sections ───────────────────────────────────────
  const lines = cvText.split('\n');

  for (const raw of lines) {
    const line = raw.trimEnd();

    // Detect ALL-CAPS section headings (e.g. PROFESSIONAL SUMMARY)
    const isSectionHeading =
      line.trim().length > 0 &&
      line.trim() === line.trim().toUpperCase() &&
      line.trim().length > 3;

    if (isSectionHeading) {
      y += 6; // breathing room before heading
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      doc.text(line.trim(), marginLeft, y);
      y += 3;
      // Underline the heading
      doc.setDrawColor(160, 160, 160);
      doc.setLineWidth(0.4);
      doc.line(marginLeft, y, pageWidth - marginRight, y);
      y += 12;
      continue;
    }

    // Empty line → paragraph gap
    if (line.trim() === '') {
      y += 6;
      continue;
    }

    // Regular body text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(30, 30, 30);

    const wrapped = doc.splitTextToSize(line, contentWidth);
    for (const wrappedLine of wrapped) {
      if (y + 14 > pageHeight - marginBottom) {
        // Add footer line on current page
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.5);
        doc.line(marginLeft, pageHeight - marginBottom + 6, pageWidth - marginRight, pageHeight - marginBottom + 6);

        doc.addPage();
        y = marginTop;
      }
      doc.text(wrappedLine, marginLeft, y);
      y += 14;
    }
  }

  // ── Footer on last page ───────────────────────────────────────────────────
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, pageHeight - marginBottom + 6, pageWidth - marginRight, pageHeight - marginBottom + 6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Aur.a · ATS-Optimised CV', pageWidth / 2, pageHeight - marginBottom + 18, {
    align: 'center',
  });

  const safeTitle = jobTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  doc.save(`personalised-cv-${safeTitle}.pdf`);
}

function safeFilePart(value: string): string {
  return value.replace(/[^a-z0-9]/gi, '-').replace(/-+/g, '-').toLowerCase() || 'cv';
}

export function downloadATSReadableCVAsPDF(cvText: string, fileNameBase: string): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  const lineHeight = 15.6; // ~13px * 1.6 line-height in pt
  let y = margin + 16;

  const ensureSpace = (height: number) => {
    if (y + height <= pageHeight - margin) return;
    doc.addPage();
    y = margin + 16;
  };

  const isHeadingLine = (t: string) =>
    t.length > 3 &&
    t === t.toUpperCase() &&
    !t.startsWith('-') &&
    !t.startsWith('\u2022') &&
    !t.includes('@');

  const lines = cvText.split('\n');

  // Line 0: Full name — centered, bold, 22pt
  const nameLine = lines[0]?.trim() ?? '';
  if (nameLine) {
    ensureSpace(28);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(0, 0, 0);
    doc.text(nameLine, pageWidth / 2, y, { align: 'center' });
    y += 20;
  }

  // Line 1: Contact line — centered, regular, 11pt
  const contactLine = lines[1]?.trim() ?? '';
  if (contactLine) {
    ensureSpace(16);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(contactLine, pageWidth / 2, y, { align: 'center' });
    y += 10;
  }

  // Top divider
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  for (let i = 2; i < lines.length; i++) {
    const trimmed = lines[i].trim();

    if (!trimmed) continue;

    if (isHeadingLine(trimmed)) {
      ensureSpace(28);
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.text(trimmed, margin, y);
      y += 4;
      doc.setDrawColor(180, 180, 180);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 10;
      continue;
    }

    // Bullet point
    if (trimmed.startsWith('-') || trimmed.startsWith('\u2022')) {
      const bulletText = trimmed.replace(/^[-\u2022]\s*/, '');
      ensureSpace(lineHeight);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      const wrapped = doc.splitTextToSize(`\u2022 ${bulletText}`, contentWidth - 16);
      for (const wl of wrapped) {
        ensureSpace(lineHeight);
        doc.text(wl, margin + 12, y);
        y += lineHeight;
      }
      continue;
    }

    // Entry header with right-aligned date
    const datePattern = /(\d{4}|Present|present)/;
    const nextTrimmed = lines[i + 1]?.trim() ?? '';
    const nextIsSubLine =
      nextTrimmed &&
      !isHeadingLine(nextTrimmed) &&
      !nextTrimmed.startsWith('-') &&
      !nextTrimmed.startsWith('\u2022');

    if (datePattern.test(trimmed) && nextIsSubLine) {
      ensureSpace(lineHeight * 2 + 4);
      y += 4;
      const match = trimmed.match(/^(.+?)\s{2,}(.+)$/);
      if (match) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        doc.text(match[1].trim(), margin, y);
        doc.setFont('helvetica', 'normal');
        doc.text(match[2].trim(), pageWidth - margin, y, { align: 'right' });
      } else {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        doc.text(trimmed, margin, y);
      }
      y += lineHeight;
      // Sub-line
      if (nextTrimmed) {
        ensureSpace(lineHeight);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        doc.text(nextTrimmed, margin, y);
        y += lineHeight;
        i++;
      }
      continue;
    }

    // Plain body text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const wrapped = doc.splitTextToSize(trimmed, contentWidth);
    for (const wl of wrapped) {
      ensureSpace(lineHeight);
      doc.text(wl, margin, y);
      y += lineHeight;
    }
  }

  doc.save(`${safeFilePart(fileNameBase)}.pdf`);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function downloadATSReadableCVAsWord(cvText: string, fileNameBase: string): void {
  const lines = cvText.split('\n');

  const isHeadingLine = (t: string) =>
    t.length > 3 &&
    t === t.toUpperCase() &&
    !t.startsWith('-') &&
    !t.startsWith('\u2022') &&
    !t.includes('@');

  const bodyParts: string[] = [];

  // Line 0: name
  const nameLine = lines[0]?.trim() ?? '';
  if (nameLine) {
    bodyParts.push(`<h1>${escapeHtml(nameLine)}</h1>`);
  }

  // Line 1: contact
  const contactLine = lines[1]?.trim() ?? '';
  if (contactLine) {
    bodyParts.push(`<p class="contact">${escapeHtml(contactLine)}</p>`);
  }

  bodyParts.push('<hr class="divider" />');

  for (let i = 2; i < lines.length; i++) {
    const trimmed = lines[i].trim();

    if (!trimmed) continue;

    if (isHeadingLine(trimmed)) {
      bodyParts.push(`<h2>${escapeHtml(trimmed)}</h2>`);
      continue;
    }

    if (trimmed.startsWith('-') || trimmed.startsWith('\u2022')) {
      const bulletText = trimmed.replace(/^[-\u2022]\s*/, '');
      bodyParts.push(`<p class="bullet">\u2022 ${escapeHtml(bulletText)}</p>`);
      continue;
    }

    // Entry header with right-aligned date
    const datePattern = /(\d{4}|Present|present)/;
    const nextTrimmed = lines[i + 1]?.trim() ?? '';
    const nextIsSubLine =
      nextTrimmed &&
      !isHeadingLine(nextTrimmed) &&
      !nextTrimmed.startsWith('-') &&
      !nextTrimmed.startsWith('\u2022');

    if (datePattern.test(trimmed) && nextIsSubLine) {
      const match = trimmed.match(/^(.+?)\s{2,}(.+)$/);
      if (match) {
        bodyParts.push(
          `<p class="entry-header"><strong>${escapeHtml(match[1].trim())}</strong><span class="date">${escapeHtml(match[2].trim())}</span></p>`
        );
      } else {
        bodyParts.push(`<p class="entry-header"><strong>${escapeHtml(trimmed)}</strong></p>`);
      }
      if (nextTrimmed) {
        bodyParts.push(`<p class="entry-sub">${escapeHtml(nextTrimmed)}</p>`);
        i++;
      }
      continue;
    }

    bodyParts.push(`<p>${escapeHtml(trimmed)}</p>`);
  }

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
body { font-family: Arial, sans-serif; color: #000000; font-size: 13px; line-height: 1.6; margin: 40px; }
h1 { font-size: 22px; font-weight: 700; text-align: center; margin: 0 0 4px; }
p.contact { font-size: 13px; font-weight: 400; text-align: center; margin: 0 0 8px; }
hr.divider { border: none; border-top: 1px solid #cccccc; margin: 4px 0 12px; }
h2 { font-size: 13px; font-weight: 700; text-transform: uppercase; margin: 14px 0 0; padding-bottom: 3px; border-bottom: 1px solid #cccccc; }
p { font-size: 13px; margin: 0 0 2px; }
p.bullet { margin-left: 16px; }
p.entry-header { display: flex; justify-content: space-between; font-weight: 700; margin-top: 6px; margin-bottom: 0; }
p.entry-header .date { font-weight: 400; }
p.entry-sub { margin: 0 0 2px; }
</style>
</head>
<body>${bodyParts.join('')}</body>
</html>`;

  const blob = new Blob([html], { type: 'application/msword;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${safeFilePart(fileNameBase)}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
