import jsPDF from 'jspdf';

/**
 * Generates a clean, ATS-friendly PDF from plain-text CV content.
 * Uses jsPDF to write real selectable text (not an image) so the PDF
 * passes ATS parsers.
 */
export function downloadCVAsPDF(cvText: string, jobTitle: string): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 56;
  const marginRight = 56;
  const marginTop = 56;
  const marginBottom = 56;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let y = marginTop;

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  const headerText = `Personalised CV — ${jobTitle}`;
  doc.text(headerText, pageWidth / 2, y, { align: 'center' });
  y += 4;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 20;

  // ── Body: parse lines and sections ───────────────────────────────────────
  const lines = cvText.split('\n');

  for (const raw of lines) {
    const line = raw.trimEnd();

    // Detect ALL-CAPS section headings (e.g. PROFESSIONAL SUMMARY)
    const isSectionHeading =
      line.trim().length > 0 &&
      line.trim() === line.trim().toUpperCase() &&
      line.trim().length > 3;

    if (isSectionHeading) {
      y += 6; // breathing room before heading
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      doc.text(line.trim(), marginLeft, y);
      y += 3;
      // Underline the heading
      doc.setDrawColor(160, 160, 160);
      doc.setLineWidth(0.4);
      doc.line(marginLeft, y, pageWidth - marginRight, y);
      y += 12;
      continue;
    }

    // Empty line → paragraph gap
    if (line.trim() === '') {
      y += 6;
      continue;
    }

    // Regular body text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(30, 30, 30);

    const wrapped = doc.splitTextToSize(line, contentWidth);
    for (const wrappedLine of wrapped) {
      if (y + 14 > pageHeight - marginBottom) {
        // Add footer line on current page
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.5);
        doc.line(marginLeft, pageHeight - marginBottom + 6, pageWidth - marginRight, pageHeight - marginBottom + 6);

        doc.addPage();
        y = marginTop;
      }
      doc.text(wrappedLine, marginLeft, y);
      y += 14;
    }
  }

  // ── Footer on last page ───────────────────────────────────────────────────
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, pageHeight - marginBottom + 6, pageWidth - marginRight, pageHeight - marginBottom + 6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Aur.a · ATS-Optimised CV', pageWidth / 2, pageHeight - marginBottom + 18, {
    align: 'center',
  });

  const safeTitle = jobTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  doc.save(`personalised-cv-${safeTitle}.pdf`);
}
